# Generated by Django 5.2.15 on 2026-07-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('target_url', models.URLField(max_length=500)),
                ('target_element', models.CharField(max_length=255)),
                ('final_status', models.CharField(default='PENDING', max_length=50)),
                ('total_steps', models.IntegerField(default=0)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_visited', models.CharField(max_length=100)),
                ('action_executed', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scraper_admin.executionhistory')),
            ],
        ),
        migrations.CreateModel(
            name='VisualLayoutCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('target_element', models.CharField(max_length=255)),
                ('healed_ymin', models.IntegerField()),
                ('healed_xmin', models.IntegerField()),
                ('healed_ymax', models.IntegerField()),
                ('healed_xmax', models.IntegerField()),
                ('absolute_click_x', models.IntegerField()),
                ('absolute_click_y', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('target_url', 'target_element')},
            },
        ),
    ]
